### ISSUE TITLE
How to run MultiK when using SCT and harmony?

### ISSUE THREAD

**Issue by Sudolin** [siyao-liu/MultiK#4]
Dear Authors,

Thanks for this incredible package. I am wondering whether we could use SCT to normalize and scale the data and  harmony to remove batch effect during each subsampling in MultiK?

**Comment by siyao-liu** [comment]
@leolambb Hi! Thanks for your interest in MultiK. You can use SCT to normalize and scale the data and just provide the normalized data output as input to read in MultiK. For Harmony batch correction, we are actively working on making MultiK compatible with integrated datasets from various batch correction methods.

**Comment by Sudolin** [comment]
Thanks for your response. Look forward to it!

**Comment by Lucas-Maciel** [comment]
Hello, just wanted to check if you have any updates about the usage of MultiK with batch correction methods such as harmony. Thanks
