### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by Lakshya3141** [siyao-liu/MultiK#6]
Hello :)
I am trying to implement MultiK on my dataset of 10k cells, however I am running into an issue of installation. All my packages and R is up to date. Below is the error I run into:
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/siyao-liu/MultiK/tarball/HEAD' failed

How should I resolve this?

**Comment by siyao-liu** [comment]
@Lakshya3141 Hi! I'm not familiar with the error message you are getting. Maybe you can you try downloading the package from the github and install it locally from your computer?

**Comment by Lakshya3141** [comment]
Thanks, that worked :)
